
services:
  app:
    &django
    restart: unless-stopped
    container_name: ${DOCKER_APP_CONTAINER}
    build:
      context: .
      dockerfile: ./deploy/Dockerfile.app
      args:
        - ENV=.env
    env_file: ./.env
    depends_on:
      - db
    networks:
      - internal
    expose:
      - ${DOCKER_UWSGI_INTERNAL_PORT}
    volumes:
      - type: volume
        source: staticfiles
        target: /shared
        volume:
          nocopy: false
      - type: volume
        source: log
        target: /log
        volume:
          nocopy: false
  server:
    container_name: ${DOCKER_WEB_CONTAINER}
    build:
      context: .
      dockerfile: ./deploy/Dockerfile.web
      args:
        - ENV=.env
    environment:
      NGINX_PORT: ${DEPLOY_WEB_PORT}
      NGINX_PROJECT: ${DOCKER_APP_CONTAINER}
      NGINX_UWSGI_INTERNAL_PORT: ${DOCKER_UWSGI_INTERNAL_PORT}
      NGINX_DAPHNE_CONTAINER: ${DOCKER_DAPHNE_CONTAINER}
      NGINX_DAPHNE_PORT: ${DOCKER_DAPHNE_PORT}
    restart: always
    networks:
      - internal
    ports:
      - "${DEPLOY_WEB_PORT}:80"
    volumes:
      - type: volume
        source: staticfiles
        target: /usr/share/nginx/html
        volume:
          nocopy: true
      - type: volume
        source: log
        target: /log
        volume:
          nocopy: false
      - ./deploy/nginx.conf:/nginx.conf.template
      - ./deploy/uwsgi_params:/etc/nginx/uwsgi_params
    depends_on:
      - app

  db:
    image: postgres:15
    restart: always
    container_name: ${DOCKER_DB_CONTAINER}
    environment:
      POSTGRES_USER: ${DOCKER_DB_USER}
      POSTGRES_PASSWORD: ${DOCKER_DB_PASSWORD}
      POSTGRES_DB: ${DOCKER_DB_DATABASE}
    env_file: ./.env
    networks:
      - internal
    volumes:
      - ./db/postgresql:/var/lib/postgresql/data/
    ports:
      - "${DOCKER_DB_PORT}:${DOCKER_DB_INNER_PORT}"

  redis:
    image: redis:5.0
    container_name: ${DOCKER_REDIS_CONTAINER}
    restart: always
    command: redis-server
    deploy:
      resources:
        limits:
          cpus: '2'
    networks:
      - internal

  daphne:
    <<: *django
    container_name: ${DOCKER_DAPHNE_CONTAINER}
    command: bash -c "daphne -b 0.0.0.0 -p ${DOCKER_DAPHNE_PORT} core.asgi:application"
    depends_on:
      - redis
    networks:
      - internal

networks:
  internal:
    name: web_crawler

volumes:
  staticfiles:
  log:
