FROM nginx:1.16
LABEL maintainer Peiyu_Jhong

COPY ./deploy/nginx.conf /etc/nginx/nginx.conf
COPY ./deploy/uwsgi_params /etc/nginx/conf.d/uwsgi_params

CMD envsubst '\$NGINX_PORT, \$NGINX_PROJECT, \$NGINX_DAPHNE_CONTAINER, \$NGINX_UWSGI_INTERNAL_PORT, \$NGINX_DAPHNE_PORT'  < /nginx.conf.template > /etc/nginx/nginx.conf && \
	exec nginx -g "daemon off;"
