# Generated by Django 5.0.6 on 2024-07-09 08:58

import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('filepath', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('news_time', models.DateTimeField()),
                ('authority', models.CharField(max_length=200)),
                ('created_time', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('title', models.CharField(max_length=300)),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_photo', to='news.image')),
            ],
        ),
    ]
